# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml\
  displayName: 'Run a multi-line script'
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/web/'
    azureSubscription: 'Visual Studio Professional with MSDN (0553e6b9-d863-45b0-91c3-93903ab4e9dd)'
    Destination: 'AzureBlob'
    storage: 'sistlainfrastructures'
    ContainerName: '$web'
    outputStorageUri: 'https://sistlainfrastructures.blob.core.windows.net/$web'